# for detailed configure instruction, see doc/deploy.md

[database]
	# SQLite3 config

	type = "sqlite3"
	path = "./oauth_application.db3"

	# MySQL config

	#type = "mysql"
	#host = "localhost"
	#port = 3306
	#db = "db-name"
	#user = "user"
	#pswd = "password"

[bili]
	# user id
	uid = 0
	# name will display on the verify request page
	nickname = ""
	user_agent = "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"

	# respond after accepting verify request
	verifyResultResp = true

[selenium]
	browserPath = ""
	options = [
		"--headless",
		"--blink-settings=imagesEnabled=false",
		# "--no-sandbox",
	]

[proxy]
	# proxy for both requests and selenium
	enable = false
	# allow HTTP proxy only
	type = "http"
	addr = "host:port"

	# set if proxy is enabled for all requests including which bearing NO credentials
	globalProxy = false

[oauth_service]
	# base64 encoded HMAC key, randomly generated if not specified.
	hmac_key = ""

[log]
	format = "[%(module)s] %(levelname)s: %(message)s"

[debug]
	seleniumTest = false
