[bili]
	# user id
	uid = 0
	# name will display on the verify request page
	nickname = ""
	user_agent = "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"

[selenium]
	path = "chromedriver"
	options = [
		"--headless",
		"--blink-settings=imagesEnabled=false",
	]

[oauth_service]
	host = "localhost"
	port = 8080

	# base64 encoded HMAC key, randomly generated if not specified.
	# we support you generate it with this shell script:
	# "head -c 64 /dev/random | base64"
	hmac_key = ""
